version: '3'

services:
  dbase:
    image: postgres
    environment:
      POSTGRES_DB: restql_demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"

  django:
    build:
      context: .
      dockerfile: django_app/Dockerfile
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django_app:/code
    ports:
      - "8000:8000"
    depends_on:
      - dbase

  flask:
    build:
      context: .
      dockerfile: flask_app/Dockerfile
    command: bash -c "flask run --host=0.0.0.0 --port=6000"
    volumes:
      - ./flask_app:/code
    ports:
      - "6000:6000"
    depends_on:
      - dbase
